### PR TITLE
Update to main.cpp (added "string reversal")

### PR DESCRIPTION
**Pull request by Kevin-Dorscher**
I have added an array to hold the items popped off the stack in reverse order, without compiling, if anyone sees any issues with the lines added, let me know.

Lines Changed:

added line 17
added line 18
added For loop inside while loop on line 36
added lines 37 - 41 (For loop comments)
NOTE: changed cout statement on line 39 to print the contents of "reverse[5]" instead of printing "iStack.Pop()".

### CODE REVIEW

**Comment by Cyberzoid1** [comment]
I like the function Idea
Currently you have a few scoping issues. For instance iStack and reverse[] are not global but under main()
What you want to do is create a new opject of Stack localy in your function to do all the work then pass the array back reversed. As a function call, no extra loop would be needed in main().

Usage
``` c++
int intArr[] = 1,2,3,4;
reverseArrary(&intArr) // function call
```
now intArr should be = 4,3,2,1

**Comment by Cyberzoid1** [comment]
A side note on how to checkout a pullrequest I added to the repo wiki.
https://github.com/CS383Team2/CS383Stack/wiki/checkout-a-pull-request

**Comment by Kevin-Dorscher** [comment]
I defined both the function and the array in main, since main already has access to the preexisting stack, all that it needed was access to the array to store values into. The reason I chose to do it this way was because, the assignment asks to create a stack, linked list, ect. So I thought using the stack we already had, would be better then creating another stack local to the "reverseString()" function.

**Comment by Kevin-Dorscher** [comment]
though, I can create an extra stack and fill the array with random values, print the array, and store the values in reverse order, and print them again if everyone would like me to.

**Comment by Cyberzoid1** [comment]
Granted since the project hasn't been specified yet, it is kinda open ended. But the assignment calls for a program that uses stacks, doesn't have to be just one.

Also having a black box that does the work then spits out the desired result is nice, clean and straight forward in my mind. It also minimized the amount of code to implement this feature directly in main. 

Also your version still has a few compiling errors in it. Needs to be fixed before it can be merged in

I would still advise making a function that takes a array then use a stack to reverse it. that way everything is scoped to only where it needs to be and avoids globals.

Some pseudo code
``` c++
int main() {
   loop push numbers
   print stack
   loop pop numbers (or pop into say an array perhaps)
   int arr[5] = {1,2,3,4,5} 
  reverseArray(arr[], size);
   // arr now reversed
}

void reverseArray(int arr[], int size) {
   make stack
   for every val in arr
       push onto stack
   
   until stack empty
      pop off stack into arr
   // arr now reversed
}
```

**Comment by Cyberzoid1** [comment]
As a general note for those who are new to git:
 I noticed that you've forked the cs383Team2 repo to your own account.
This is fine and would be the way to contribute to a repo that you do not own or have direct access to. 
You are currently working with your fork so your process would be fork > commit/code your local repo then create a pull request to the CS383Team2/CS383Stack repo with your provided commit alteration.

With this repo you also have direct write access to the CS383Team2CS383Stack repo. That means you can push directly to the project. That would mean you clone the CS383Team2CS383Stack repo and work with it not a fork.
I would recommend creating your own branch to do your dev work then merge (fast-forward merge if nobody else has changed master) into master when your code is stable. Dont forget to merge master into your own branch to get any new commits or rebase your branch to the latest master commit if you want to start from the latest master.

**Pull request closed without merging**
